name: firstapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data.json
    - assets/longmao.png

  fonts:
    - family: maa
      fonts:
        - asset: fonts/maaja.ttf

# ✅ flutter_icons 必须放在 flutter 外面
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icons.png"
